version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: Kuinhoe_Database
      POSTGRES_USER: Kuinhoe_User
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5432:5432

