spring:
    application:
         name: kuinhoe
    datasource:
        url: jdbc:postgresql://localhost:5432/Kuinhoe_Database
        username: Kuinhoe_User
        password: qwerty
        driver-class-name: org.postgresql.Driver
    jpa: 
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format-sql: true